---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
before_install: gem install bundler -v 1.17.1
script:
  - bundle exec rake test
  - bundle exec rubocop
  - bundle exec bundle-audit check --update
